/**
 * Generan descripciones para las 5 comunidades de la plataforma
 * (development, marketing, design, communication, entertainment)
 * y dependiendo de la comunidad especificada devolverá un string
 * con la información, ya sea desde una perspectiva impersonal
 * o personal.
 */

import { Skill } from "@/src/shared/types/atoms/select.type";

export const getMyCommunityInfo = (community: string | undefined): string => {
    switch (community) {
        case "Desarrollo":
            return `Tu comunidad es Desarrollo. Aquí viven las mentes inquietas del código y amantes de los retos lógicos que transforman ideas en realidad digital. 🚀💻`;
        case "Marketing":
            return `Tu comunidad es Marketing. Estás rodeado de creativos y estrategas, con un olfato increíble para las tendencias. ¡Saben cómo hacer que el mundo los escuche! 📈🎯`;
        case "Comunicación":
            return `Tu comunidad es Comunicación. Aquí reinan los que dominan las palabras, conectan con el mundo y saben cómo contar historias que inspiran. 🗣️✨`;
        case "Diseño":
            return `Tu comunidad es Diseño. Estás entre artistas visuales, creadores de experiencias y amantes de lo estético. Ven la belleza donde otros no la notan. 🎨🧠`;
        case "Entretenimiento":
            return `Tu comunidad es Entretenimiento. Aquí se vibra alto con creatividad, carisma y pasión por hacer reír, emocionar y entretener al mundo. 🎭📺`;
        default:
            return `¡Ups! Aún no reconocemos esta comunidad, pero seguro que es igual de genial. 😎`;
    }
};

export const getCommunityInfo = (community: string | undefined): string => {
    switch (community) {
        case "Desarrollo":
            return `La comunidad de este usuario es Desarrollo. Aquí se encuentran las mentes inquietas del código y amantes de los retos lógicos que transforman ideas en realidad digital. 🚀💻`;
        case "Marketing":
            return `La comunidad de este usuario es Marketing. Está rodeado de creativos y estrategas, con un olfato increíble para las tendencias. ¡Saben cómo hacer que el mundo los escuche! 📈🎯`;
        case "Comunicación":
            return `La comunidad de este usuario es Comunicación. Aquí reinan los que dominan las palabras, conectan con el mundo y saben cómo contar historias que inspiran. 🗣️✨`;
        case "Diseño":
            return `La comunidad de este usuario es Diseño. Está entre artistas visuales, creadores de experiencias y amantes de lo estético. Ven la belleza donde otros no la notan. 🎨🧠`;
        case "Entretenimiento":
            return `La comunidad de este usuario es Entretenimiento. Aquí se vibra alto con creatividad, carisma y pasión por hacer reír, emocionar y entretener al mundo. 🎭📺`;
        default:
            return `¡Ups! Aún no reconocemos esta comunidad, pero seguro que es igual de genial. 😎`;
    }
};

/**
 *  Genera habilidades digitales categorizadas para las 5 comunidades de la
 *  plataforma (development, marketing, design, communication, entertainment)
 *  y devuelve un único array con todas las skills bajo este modelo:
 * 
 *  type Skill = {
        name: string;
        aliases: string[];
        related?: string[];
    };
 */

export const getAllSkills = (): Skill[] => {
    const development = [
        { name: "AWS", aliases: ["Amazon Web Services"], related: ["Nube", "Serverless"] },
        { name: "HTML", aliases: ["HyperText Markup Language", "HTML5"], related: ["CSS", "JavaScript", "Desarrollo Web"] },
        { name: "CSS", aliases: ["Cascading Style Sheets"], related: ["HTML", "Tailwind CSS", "Bootstrap"] },
        { name: "JavaScript", aliases: ["JS"], related: ["React", "Node.js", "Frontend", "Backend"] },
        { name: "TypeScript", aliases: ["TS"], related: ["JavaScript", "React", "Next.js"] },
        { name: "Java", aliases: [], related: ["Spring Boot", "Backend"] },
        { name: "React", aliases: ["ReactJS"], related: ["JavaScript", "Next.js", "TypeScript", "Frontend", "Vite"] },
        { name: "Python", aliases: [], related: ["Django", "Flask", "Machine Learning", "Data Engineering"] },
        { name: "Django", aliases: [], related: ["Python", "Backend", "API"] },
        { name: "Flask", aliases: [], related: ["Python", "Backend", "API"] },
        { name: "Express", aliases: ["ExpressJS"], related: ["Node.js", "Backend", "API"] },
        { name: "Next.js", aliases: ["Next"], related: ["React", "Node.js", "TypeScript", "JavaScript", "Frontend"] },
        { name: "Node.js", aliases: ["Node"], related: ["Express", "TypeScript", "JavaScript", "Backend"] },
        { name: "Ruby", aliases: ["RubyLang", "Ruby on Rails"], related: ["Backend"] },
        { name: "Swift", aliases: ["SwiftLang", "SwiftUI", "Xcode"], related: ["iOS", "Mobile", "Programación"] },
        { name: "Vercel", aliases: [], related: ["Hosting", "Next.js", "Frontend", "Serverless", "Edge Computing"] },
        { name: "Netlify", aliases: [], related: ["Hosting", "Frontend", "Serverless", "CI/CD"] },
        { name: "NestJS", aliases: ["Nest"], related: ["Node.js", "Backend", "TypeScript", "API", "Microservicios"] },
        { name: "Apache", aliases: ["Apache HTTP Server"], related: ["Desarrollo Web", "Hosting", "Backend", "Linux"] },
        { name: "Nube", aliases: ["Computación en la Nube", "Cloud", "Cloud Computing"], related: ["AWS", "Azure", "Serverless", "Docker", "Kubernetes", "Render Cloud", "Edge Computing"] },
        { name: "Spring Boot", aliases: ["Spring"], related: ["Java", "Backend"] },
        { name: "Encriptación", aliases: ["Encryption", "Cifrado", "SSL/TLS", "HTTPS"], related: ["Ciberseguridad", "JWT", "OAuth"] },
        { name: "Programación", aliases: ["Coding", "Desarrollo"], related: ["Algoritmia", "Estructura de Datos", "Lógica", "Backend", "Frontend"] },
        { name: "Swagger", aliases: ["OpenAPI"], related: ["API", "Backend"] },
        { name: "C", aliases: [], related: ["C++", "Hardware"] },
        { name: "C#", aliases: ["C Sharp"], related: [".NET", "Backend"] },
        { name: "C++", aliases: ["Cpp"], related: ["C", "Hardware"] },
        { name: "NPM", aliases: ["Packages", "Node Package Manager"], related: ["Librerías", "Node.js", "JavaScript", "TypeScript"] },
        { name: ".NET", aliases: [], related: ["C#", "Backend"] },
        { name: "PHP", aliases: [], related: ["Laravel", "Backend"] },
        { name: "Laravel", aliases: [], related: ["PHP", "Backend"] },
        { name: "JSON", aliases: [], related: ["API", "JavaScript"] },
        { name: "API", aliases: [], related: ["RESTful", "GraphQL", "Swagger"] },
        { name: "RESTful", aliases: [], related: ["API", "Node.js", "Backend"] },
        { name: "Soporte Técnico", aliases: ["Technical Support"], related: ["Hardware", "Software"] },
        { name: "CRUD", aliases: [], related: ["API", "Backend"] },
        { name: "NoSQL", aliases: [], related: ["MongoDB", "Firebase"] },
        { name: "SQL", aliases: [], related: ["MySQL", "PostgreSQL", "Bases de Datos"] },
        { name: "MySQL", aliases: [], related: ["SQL", "Backend"] },
        { name: "PostgreSQL", aliases: [], related: ["SQL", "Backend"] },
        { name: "MongoDB", aliases: [], related: ["NoSQL", "Backend"] },
        { name: "GraphQL", aliases: [], related: ["API", "Frontend", "React"] },
        { name: "Bases de Datos", aliases: ["Databases"], related: ["SQL", "NoSQL", "MySQL", "MongoDB", "PostgreSQL"] },
        { name: "Realidad Aumentada", aliases: ["AR"], related: ["Realidad Virtual", "Hardware"] },
        { name: "Realidad Virtual", aliases: ["VR"], related: ["Realidad Aumentada", "Hardware"] },
        { name: "Docker", aliases: [], related: ["Kubernetes", "CI/CD", "Backend"] },
        { name: "Kubernetes", aliases: ["K8s"], related: ["Docker", "CI/CD"] },
        { name: "Linux", aliases: [], related: ["Backend", "Serverless", "Docker"] },
        { name: "Windows", aliases: [], related: ["Software", "Backend"] },
        { name: "iOS", aliases: [], related: ["Mobile", "Swift"] },
        { name: "Android", aliases: [], related: ["Mobile", "Flutter"] },
        { name: "Render Cloud", aliases: [], related: ["Nube", "Backend"] },
        { name: "Azure", aliases: [], related: ["Nube", "Serverless"] },
        { name: "IoT", aliases: ["Internet of Things", "Internet de las Cosas"], related: ["Hardware", "Electrónica"] },
        { name: "Git", aliases: ["GitFlow"], related: ["GitHub", "CI/CD"] },
        { name: "GitHub", aliases: ["GitHub Actions", "GitFlow"], related: ["Git", "CI/CD"] },
        { name: "Inteligencia Artificial", aliases: ["AI", "IA", "Claude", "ChatGPT", "Gemini", "LLMs", "Modelos de Lenguaje"], related: ["Machine Learning", "Deep Learning", "Python", "Prompts", "NLP"] },
        { name: "Machine Learning", aliases: ["ML"], related: ["Python", "Inteligencia Artificial", "Data Engineering"] },
        { name: "Backend", aliases: [], related: ["Node.js", "Python", "API"] },
        { name: "Frontend", aliases: [], related: ["React", "Next.js", "CSS", "HTML"] },
        { name: "Full Stack", aliases: [], related: ["Frontend", "Backend", "Software"] },
        { name: "CI/CD", aliases: [], related: ["Docker", "Kubernetes", "GitHub"] },
        { name: "Flutter", aliases: [], related: ["Dart", "Mobile", "React Native"] },
        { name: "Dart", aliases: [], related: ["Flutter"] },
        { name: "React Native", aliases: [], related: ["React", "Flutter", "Mobile"] },
        { name: "Mobile", aliases: ["Apps"], related: ["Flutter", "React Native", "iOS", "Android"] },
        { name: "Jest", aliases: [], related: ["Testing", "Frontend", "React"] },
        { name: "Playwright", aliases: [], related: ["Testing", "Frontend", "Backend"] },
        { name: "Prisma", aliases: [], related: ["Node.js", "Backend", "SQL"] },
        { name: "Vite", aliases: [], related: ["Frontend", "React", "React Native"] },
        { name: "Webpack", aliases: [], related: ["Frontend", "React"] },
        { name: "Sass", aliases: [], related: ["CSS", "Frontend"] },
        { name: "Styled Components", aliases: ["SC"], related: ["React", "CSS"] },
        { name: "Tailwind CSS", aliases: [], related: ["CSS", "Frontend"] },
        { name: "Bootstrap", aliases: [], related: ["CSS", "Frontend"] },
        { name: "Ciencia de Datos", aliases: ["Data Science"], related: ["Python", "Machine Learning", "Pandas", "NumPy"] },
        { name: "Software", aliases: [], related: ["Windows", "Linux", "iOS", "Android", "Mobile", "Desarrollo Web", "Frontend", "Backend", "Full Stack"] },
        { name: "Hardware", aliases: [], related: ["IoT", "C++", "Electrónica", "Física", "Soporte Técnico"] },
        { name: "Hosting", aliases: [], related: ["Backend", "Nube"] },
        { name: "VPN", aliases: [], related: ["Ciberseguridad"] },
        { name: "Control de Calidad (QA)", aliases: ["Quality Assurance"], related: ["Testing", "Jest"] },
        { name: "Desarrollo Web", aliases: ["Web Development"], related: ["HTML", "CSS", "Frontend"] },
        { name: "Testing", aliases: [], related: ["Jest", "Playwright", "Control de Calidad (QA)"] },
        { name: "Microservicios", aliases: [], related: ["Backend", "Docker", "Kubernetes"] },
        { name: "Electrónica", aliases: [], related: ["IoT", "Hardware", "Ciencia"] },
        { name: "Biometría", aliases: [], related: ["IoT", "Hardware"] },
        { name: "Física", aliases: [], related: ["Hardware", "Electrónica", "Ciencia"] },
        { name: "Lógica", aliases: ["Maths", "Logic", "Matemáticas"], related: ["Algoritmia", "Programación", "Ciencia"] },
        { name: "Algoritmia", aliases: ["Algorithms"], related: ["Lógica", "Programación"] },
        { name: "Ciencia", aliases: ["Science", "Chemistry", "Química"], related: ["Física", "Lógica", "Electrónica"] },
        { name: "Robótica", aliases: [], related: ["Automatización", "Electrónica", "IoT", "Hardware", "Inteligencia Artificial"] },
        { name: "Librerías", aliases: ["Gestión de Paquetes", "Package Management", "NPM Packages"], related: ["NPM", "Node.js", "JavaScript", "TypeScript", "Frontend", "Backend"] },
        { name: "Ingeniería de Requisitos", aliases: [], related: ["Arquitectura de Software", "Scrum"] },
        { name: "Patrones de Arquitectura", aliases: [], related: ["Arquitectura de Software", "Patrones de Diseño"] },
        { name: "Patrones de Diseño", aliases: [], related: ["Patrones de Arquitectura", "Clean Code"] },
        { name: "Estructura de Datos", aliases: [], related: ["Algoritmia", "Programación"] },
        { name: "Redis", aliases: [], related: ["Backend", "NoSQL"] },
        { name: "Firebase", aliases: [], related: ["NoSQL", "Backend"] },
        { name: "Supabase", aliases: [], related: ["Backend", "NoSQL"] },
        { name: "WebSockets", aliases: [], related: ["API"] },
        { name: "gRPC", aliases: [], related: ["API", "Backend"] },
        { name: "Serverless", aliases: [], related: ["AWS", "Azure", "Backend"] },
        { name: "Edge Computing", aliases: [], related: ["Serverless", "Nube"] },
        { name: "Arquitectura de Software", aliases: [], related: ["Patrones de Arquitectura", "Backend"] },
        { name: "Clean Code", aliases: [], related: ["Patrones de Diseño", "TDD"] },
        { name: "TDD", aliases: ["Test Driven Development"], related: ["Clean Code", "Testing"] },
        { name: "Scrum", aliases: [], related: ["Kanban", "Ingeniería de Requisitos"] },
        { name: "Kanban", aliases: [], related: ["Scrum", "Gestión de Proyectos"] },
        { name: "DevOps", aliases: [], related: ["CI/CD", "Docker", "Kubernetes"] },
        { name: "Ciberseguridad", aliases: ["Web Security", "Cybersecurity"], related: ["OAuth", "JWT", "VPN"] },
        { name: "OAuth", aliases: [], related: ["JWT", "Ciberseguridad"] },
        { name: "JWT", aliases: ["JSON Web Token"], related: ["OAuth", "Ciberseguridad"] },
        { name: "Prompts", aliases: ["Prompt Engineering", "AI Prompting", "Instrucciones AI"], related: ["Inteligencia Artificial", "NLP", "Redacción", "Copywriting", "Automatización"] },
        { name: "Deep Learning", aliases: [], related: ["Inteligencia Artificial", "Python"] },
        { name: "NLP", aliases: ["Natural Language Processing"], related: ["Python", "Machine Learning", "Prompts", "Inteligencia Artificial"] },
        { name: "Computer Vision", aliases: [], related: ["Python", "Machine Learning"] },
        { name: "Big Data", aliases: [], related: ["Data Engineering", "Python"] },
        { name: "Data Engineering", aliases: [], related: ["Python", "Big Data", "ETL"] },
        { name: "ETL", aliases: ["Extract Transform Load"], related: ["Data Engineering", "SQL"] },
        { name: "Power BI", aliases: [], related: ["Data Engineering", "Análisis de Datos"] },
        { name: "Tableau", aliases: [], related: ["Data Engineering", "Análisis de Datos"] },
        { name: "Pandas", aliases: [], related: ["Python", "Ciencia de Datos"] },
        { name: "NumPy", aliases: [], related: ["Python", "Ciencia de Datos"] },
    ];

    const marketing = [
        { name: "SEO", aliases: ["Search Engine Optimization"], related: ["SEM", "Google Ads", "Marketing de Contenidos"] },
        { name: "SEM", aliases: ["Search Engine Marketing"], related: ["SEO", "Google Ads", "Performance Digital", "PPC"] },
        { name: "PPC", aliases: ["Pay Per Click", "Paid Search", "PPC Advertising", "PPC Marketing", "Pago Por Clic"], related: ["SEM", "Google Ads", "Meta Ads", "Performance Digital", "Remarketing", "Optimización de Conversiones"] },
        { name: "Google Ads", aliases: [], related: ["SEM", "SEO", "Performance Digital", "PPC"] },
        { name: "Meta Ads", aliases: ["Facebook Ads"], related: ["Performance Digital", "Redes Sociales", "PPC"] },
        { name: "Email Marketing", aliases: [], related: ["Marketing de Contenidos", "Automatización"] },
        { name: "Gestión Empresarial", aliases: ["Business Management"], related: ["Administración", "Costos y Presupuestos"] },
        { name: "Costos y Presupuestos", aliases: ["Budgeting"], related: ["Administración", "Gestión Empresarial"] },
        { name: "Gestión de Contenidos", aliases: ["Content Management"], related: ["Producción de Contenido", "Gestión de Comunidad", "Curaduría Multimedia"] },
        { name: "UGC", aliases: ["User Generated Content"], related: ["Creador de Contenido"] },
        { name: "Engagement", aliases: ["User Engagement", "Interacción"], related: ["Retención de Usuarios", "Growth Hacking", "Customer Journey", "Redes Sociales"] },
        { name: "Performance Digital", aliases: ["Rendimiento"], related: ["SEM", "Google Ads", "Optimización de Conversiones", "PPC"] },
        { name: "Marketing de Contenidos", aliases: ["Content Marketing"], related: ["SEO", "Email Marketing", "Gestión de Contenidos"] },
        { name: "Embudo de Conversión", aliases: ["Conversion Funnel"], related: ["CRO", "Customer Journey", "Optimización de Conversiones"] },
        { name: "CRO", aliases: ["Conversion Rate Optimization"], related: ["Embudo de Conversión", "Optimización de Conversiones"] },
        { name: "Customer Journey", aliases: ["Viaje del Cliente"], related: ["Embudo de Conversión", "Retención de Usuarios"] },
        { name: "Branding", aliases: [], related: ["Posicionamiento de Marca", "Identidad de Marca"] },
        { name: "Retención de Usuarios", aliases: ["User Retention"], related: ["Customer Journey", "Growth Hacking", "Engagement"] },
        { name: "Growth Hacking", aliases: [], related: ["Retención de Usuarios", "Performance Digital", "Engagement"] },
        { name: "Automatización", aliases: ["Marketing Automation"], related: ["Email Marketing", "Gestión de CRM"] },
        { name: "Gestión de CRM", aliases: [], related: ["Automatización", "Customer Journey"] },
        { name: "Google Analytics", aliases: [], related: ["Cookies y Tracking", "Análisis de Datos"] },
        { name: "Posicionamiento de Marca", aliases: ["Brand Positioning"], related: ["Branding", "Marketing de Contenidos"] },
        { name: "Copywriting", aliases: [], related: ["Redacción", "Marketing de Contenidos"] },
        { name: "Optimización de Conversiones", aliases: ["Conversion Optimization"], related: ["CRO", "Embudo de Conversión", "PPC"] },
        { name: "Análisis de Datos", aliases: ["Data Analysis"], related: ["Google Analytics", "Power BI", "Tableau"] },
        { name: "Remarketing", aliases: ["Retargeting"], related: ["Google Ads", "Meta Ads", "PPC"] },
        { name: "Estrategias de Mercado", aliases: ["Market Strategies"], related: ["Investigación de Mercado", "Marketing de Contenidos"] },
        { name: "E-commerce", aliases: ["Comercio Electrónico"], related: ["Performance Digital", "Marketing de Contenidos"] },
        { name: "Pruebas A/B", aliases: ["A/B Testing"], related: ["Optimización de Conversiones", "CRO"] },
        { name: "Hashtags", aliases: [], related: ["Redes Sociales"] },
        { name: "Leads", aliases: [], related: ["Customer Journey", "Embudo de Conversión"] },
        { name: "Seguimiento de KPIs", aliases: ["KPI Tracking"], related: ["Análisis de Datos", "Performance Digital"] },
        { name: "Campañas", aliases: ["Marketing Campaigns"], related: ["Performance Digital", "Google Ads", "PPC"] },
        { name: "Investigación de Mercado", aliases: ["Market Research"], related: ["Estrategias de Mercado", "Globalización"] },
        { name: "Gestión de Productos", aliases: ["Product Management"], related: ["Administración", "Marketing de Contenidos"] },
        { name: "Alianzas", aliases: ["Partnerships"], related: ["Negociación", "Globalización", "Colaboraciones", "Curaduría Multimedia"] },
        { name: "Negociación", aliases: ["Negotiation"], related: ["Alianzas", "Proveedores"] },
        { name: "Localización de Mercado", aliases: ["Market Localization"], related: ["Globalización", "Glocalización"] },
        { name: "Globalización", aliases: ["Globalization"], related: ["Localización de Mercado", "Internacionalización"] },
        { name: "Glocalización", aliases: ["Glocalization"], related: ["Localización de Mercado", "Globalización"] },
        { name: "Franquicias", aliases: ["Franchises"], related: ["Expansión Comercial", "Administración"] },
        { name: "Administración", aliases: ["Management", "Manager", "Representante"], related: ["Gestión Empresarial", "Costos y Presupuestos"] },
        { name: "Expansión Comercial", aliases: ["Business Expansion"], related: ["Franquicias", "Ventas"] },
        { name: "Ventas", aliases: ["Sales"], related: ["Expansión Comercial", "Customer Journey"] },
        { name: "Internacionalización", aliases: ["Internationalization"], related: ["Globalización", "Estrategias de Mercado"] },
        { name: "Regulaciones", aliases: ["Regulations"], related: ["Compliance Marketing", "Cookies y Tracking"] },
        { name: "Cookies y Tracking", aliases: ["Seguimiento"], related: ["Google Analytics", "Performance Digital"] },
        { name: "Compliance Marketing", aliases: [], related: ["Regulaciones", "Marketing de Contenidos"] },
        { name: "Afiliados", aliases: ["Affiliate Marketing"], related: ["Monetización", "PYMES"] },
        { name: "PYMES", aliases: ["Small and Medium Enterprises"], related: ["Afiliados", "Proveedores"] },
        { name: "Monetización", aliases: ["Monetization"], related: ["Afiliados", "Performance Digital"] },
        { name: "Proveedores", aliases: ["Suppliers"], related: ["Negociación", "PYMES"] },
        { name: "Video Marketing", aliases: [], related: ["YouTube", "Marketing de Contenidos"] },
        { name: "Podcast Marketing", aliases: [], related: ["Podcast", "Marketing de Contenidos"] },
    ];

    const design = [
        { name: "Diseño UI", aliases: ["UI Design"], related: ["Diseño UX", "Diseño Web", "Diseño Interactivo"] },
        { name: "Diseño UX", aliases: ["UX Design"], related: ["Diseño UI", "Investigación UX", "Prototipado", "Heurísticas UX"] },
        { name: "Diseño Gráfico", aliases: ["Graphic Design"], related: ["Diseño Web", "Adobe Illustrator", "Tipografía"] },
        { name: "Diseño Crossmedia", aliases: [], related: ["Diseño Interactivo", "Marketing de Contenidos"] },
        { name: "Diseño Web", aliases: ["Web Design"], related: ["HTML", "CSS", "Diseño UI"] },
        { name: "Diseño Interactivo", aliases: ["Interactive Design"], related: ["Diseño UX", "Motion UI"] },
        { name: "Diseño de Producto", aliases: ["Product Design"], related: ["Prototipado", "Design Thinking"] },
        { name: "Diseño de Espacios", aliases: ["Interior Design", "Diseño de Interiores", "Diseño de Ambientes"], related: ["Arquitectura 3D", "Revit"] },
        { name: "Identidad de Marca", aliases: ["Brand Identity"], related: ["Branding", "Logotipado"] },
        { name: "Tipografía", aliases: ["Typography"], related: ["Diseño Gráfico", "Diseño Editorial"] },
        { name: "Teoría del Color", aliases: ["Color Theory"], related: ["Diseño Gráfico", "Corrección de Color"] },
        { name: "Maquetación", aliases: ["Layout Design"], related: ["Diseño Editorial", "Diseño Web"] },
        { name: "Investigación UX", aliases: [], related: ["Pruebas de Usabilidad", "Design Thinking"] },
        { name: "Ilustración", aliases: ["Dibujo", "Drawing", "Cómic", "Anime", "Manga", "Illustration"], related: ["Concept Art", "Arte Digital", "Adobe Illustrator", "Diseño Gráfico"] },
        { name: "Gráficos en Movimiento", aliases: ["Motion Graphics"], related: ["Adobe After Effects", "Motion UI"] },
        { name: "Modelado 3D", aliases: ["3D Modeling"], related: ["Blender", "Maya", "ZBrush"] },
        { name: "Prototipado", aliases: ["Prototyping"], related: ["Diseño UX", "Diseño de Producto", "Figma"] },
        { name: "Canva", aliases: [], related: ["Presentaciones", "Diseño Gráfico"] },
        { name: "Figma", aliases: [], related: ["Prototipado", "Wireframing", "Sistemas de Diseño"] },
        { name: "Adobe XD", aliases: [], related: ["Prototipado", "Wireframing", "Diseño UX"] },
        { name: "Adobe Photoshop", aliases: [], related: ["Diseño Gráfico", "Edición de Imagen", "Ilustración"] },
        { name: "Adobe Illustrator", aliases: [], related: ["Diseño Gráfico", "Ilustración", "Logotipado"] },
        { name: "Adobe Premiere", aliases: [], related: ["Edición de Video", "Postproducción"] },
        { name: "Adobe Substance", aliases: [], related: ["Modelado 3D", "Texturizado"] },
        { name: "ZBrush", aliases: [], related: ["Modelado 3D", "Creación de Personajes"] },
        { name: "SketchUp", aliases: [], related: ["Diseño de Espacios", "Arquitectura 3D"] },
        { name: "Revit", aliases: [], related: ["Arquitectura 3D", "Diseño de Espacios"] },
        { name: "AutoCAD", aliases: [], related: ["Arquitectura 3D", "Diseño de Espacios"] },
        { name: "Adobe After Effects", aliases: [], related: ["Gráficos en Movimiento", "Motion UI", "Postproducción"] },
        { name: "Arquitectura 3D", aliases: ["3D Architecture"], related: ["Urbanismo", "Diseño de Espacios", "Revit"] },
        { name: "Urbanismo", aliases: ["Urban Planning"], related: ["Arquitectura 3D", "Globalización"] },
        { name: "Cinema 4D", aliases: [], related: ["Modelado 3D", "Motion UI"] },
        { name: "Maya", aliases: [], related: ["Modelado 3D", "Animación 3D"] },
        { name: "Renderizado", aliases: ["Rendering"], related: ["Render Cloud", "Modelado 3D"] },
        { name: "Texturizado", aliases: ["Texturing"], related: ["Adobe Substance", "Modelado 3D"] },
        { name: "Rigging", aliases: [], related: ["Modelado 3D", "Animación 3D"] },
        { name: "Microcopy", aliases: [], related: ["Redacción UX", "Diseño UX"] },
        { name: "Blender", aliases: [], related: ["Modelado 3D", "Animación 3D", "Arquitectura 3D"] },
        { name: "Sistemas de Diseño", aliases: ["Design Systems"], related: ["Figma", "Bibliotecas de Componentes"] },
        { name: "Wireframing", aliases: ["Wireframes", "Mock Up"], related: ["Figma", "Adobe XD", "Diseño UX"] },
        { name: "Flowchart", aliases: ["Diagramas de Flujo"], related: ["Wireframing", "Diseño UX"] },
        { name: "Diseño Responsivo", aliases: ["Responsive Design"], related: ["Diseño Web", "CSS"] },
        { name: "Accesibilidad", aliases: ["Accessibility"], related: ["Diseño UX", "Diseño Responsivo"] },
        { name: "Dirección de Vestuario", aliases: ["Costume Direction"], related: ["Dirección Creativa", "Diseño de Modas"] },
        { name: "Diseño de Modas", aliases: ["Fashion Design"], related: ["Dirección de Vestuario", "Dirección Creativa"] },
        { name: "Dirección Creativa", aliases: ["Creative Direction"], related: ["Dirección de Vestuario", "Diseño de Modas", "Dirección de Arte"] },
        { name: "Design Thinking", aliases: [], related: ["Diseño de Producto", "Investigación UX", "Prototipado", "Pruebas de Usabilidad"] },
        { name: "Pruebas de Usabilidad", aliases: ["Usability Testing", "Test de Usabilidad"], related: ["Investigación UX", "Diseño UX", "Heurísticas UX", "Design Thinking"] },
        { name: "Dirección de Arte", aliases: ["Art Direction"], related: ["Dirección Creativa", "Diseño Editorial"] },
        { name: "Diseño de Interacción", aliases: ["Interaction Design"], related: ["Diseño UX", "Microinteracciones"] },
        { name: "Bibliotecas de Componentes", aliases: ["Component Libraries"], related: ["Sistemas de Diseño", "Figma", "Librerías", "Frameworks"] },
        { name: "Logotipado", aliases: ["Logo Design"], related: ["Identidad de Marca", "Diseño Gráfico"] },
        { name: "Diseño Editorial", aliases: ["Editorial Design"], related: ["Diseño Gráfico", "Tipografía", "Maquetación"] },
        { name: "Frameworks", aliases: [], related: ["Tailwind CSS", "Bootstrap", "Vite"] },
        { name: "Redacción UX", aliases: ["UX Writing"], related: ["Microcopy", "Diseño UX"] },
        { name: "Microinteracciones", aliases: ["Microinteractions"], related: ["Diseño de Interacción", "Motion UI"] },
        { name: "Motion UI", aliases: [], related: ["Gráficos en Movimiento", "Microinteracciones"] },
        { name: "Tokens de Diseño", aliases: ["Design Tokens"], related: ["Sistemas de Diseño", "Atomic Design"] },
        { name: "Atomic Design", aliases: [], related: ["Tokens de Diseño", "Sistemas de Diseño"] },
        { name: "Heurísticas UX", aliases: ["Usability Heuristics"], related: ["Pruebas de Usabilidad", "Diseño UX"] },
    ];

    const communication = [
        { name: "Oratoria", aliases: [], related: ["Presentaciones", "Stand Up", "Vocalización", "Discursos"] },
        { name: "Estrategias de Contenido", aliases: [], related: ["Marketing de Contenidos", "Producción de Contenido"] },
        { name: "Relaciones con Medios", aliases: [], related: ["Comunicación Corporativa", "Notas de Prensa"] },
        { name: "Comunicación de Crisis", aliases: ["Crisis Communication"], related: ["Relaciones con Medios", "Comunicación Interna"] },
        { name: "Redacción", aliases: [], related: ["Escritura Creativa", "Ghostwriting"] },
        { name: "Discursos", aliases: ["Speeches"], related: ["Oratoria", "Presentaciones"] },
        { name: "Vocalización", aliases: [], related: ["Oratoria", "Locución"] },
        { name: "Fonética", aliases: [], related: ["Vocalización", "Idiomas"] },
        { name: "Idiomas", aliases: ["Inglés", "Español", "Catalán", "Indígena", "Africano", "Francés", "Alemán", "Japonés", "Coreano", "Chino", "Portugués", "Italiano", "Ruso", "Languages", "Lenguas Extranjeras"], related: ["Comunicación Intercultural", "Fonética"] },
        { name: "Gramática", aliases: [], related: ["Redacción", "Escritura Creativa"] },
        { name: "Ghostwriting", aliases: [], related: ["Redacción", "Escritura Creativa"] },
        { name: "Derechos de Autor", aliases: [], related: ["Literatura", "Redacción"] },
        { name: "Literatura", aliases: [], related: ["Redacción", "Escritura Creativa"] },
        { name: "Edición de Textos", aliases: [], related: ["Redacción", "Escritura Creativa"] },
        { name: "Narrativa Transmedia", aliases: [], related: ["Storytelling", "Producción de Contenido", "Diseño UX", "Diseño UI", "Creador de Contenido"] },
        { name: "Gestión de Comunidad", aliases: ["Community Management", "Community Manager", "Representante"], related: ["Gestión de Contenidos", "Redes Sociales", "Curaduría Multimedia", "Marketing de Contenidos"] },
        { name: "Redes Sociales", aliases: ["Social Media"], related: ["Gestión de Comunidad", "Instagram", "TikTok"] },
        { name: "Comunicación Interna", aliases: [], related: ["Comunicación Corporativa", "Comunicación de Crisis"] },
        { name: "Comunicación Corporativa", aliases: [], related: ["Relaciones con Medios", "Comunicación Interna"] },
        { name: "Entrevistas", aliases: [], related: ["Periodismo", "Locución"] },
        { name: "Producción de Contenido", aliases: [], related: ["Estrategias de Contenido", "Edición de Video"] },
        { name: "Podcast", aliases: ["Podcast Marketing"], related: ["Locución", "Producción de Contenido"] },
        { name: "Locución", aliases: [], related: ["Vocalización", "Podcast"] },
        { name: "Blog", aliases: ["Blogging"], related: ["Redacción", "Marketing de Contenidos", "SEO"] },
        { name: "Vlog", aliases: ["Video Blogging"], related: ["Creador de Contenido", "Edición de Video", "YouTube"] },
        { name: "Revista Digital", aliases: ["Magazine"], related: ["Periodismo", "Diseño Editorial", "Redacción"] },
        { name: "Improvisación", aliases: ["Improvisation"], related: ["Actuación", "Stand Up", "Oratoria"] },
        { name: "Doblaje", aliases: [], related: ["Locución", "Actuación"] },
        { name: "Periodismo", aliases: [], related: ["Entrevistas", "Notas de Prensa"] },
        { name: "Guionismo", aliases: [], related: ["Producción de Contenido", "Narrativa Transmedia"] },
        { name: "Mensaje de Marca", aliases: [], related: ["Branding", "Storytelling"] },
        { name: "Storytelling", aliases: ["Cuentería"], related: ["Narrativa Transmedia", "Presentaciones"] },
        { name: "Persuasión", aliases: [], related: ["Copywriting", "Presentaciones"] },
        { name: "Presentaciones", aliases: [], related: ["Oratoria", "Discursos"] },
        { name: "Pitching", aliases: [], related: ["Presentaciones", "Persuasión"] },
        { name: "Escritura Creativa", aliases: [], related: ["Redacción", "Literatura"] },
        { name: "Comunicación Intercultural", aliases: [], related: ["Idiomas", "Networking"] },
        { name: "Comunicación Visual", aliases: [], related: ["Diseño UI", "Diseño UX"] },
        { name: "Notas de Prensa", aliases: [], related: ["Relaciones con Medios", "Periodismo"] },
        { name: "Portafolio", aliases: [], related: ["LinkedIn", "Diseño UX"] },
        { name: "LinkedIn", aliases: [], related: ["Networking", "Portafolio"] },
        { name: "Habilidades Blandas", aliases: ["Soft Skills"], related: ["Networking", "Moderación", "Psicología"] },
        { name: "Networking", aliases: [], related: ["LinkedIn", "Comunicación Intercultural"] },
        { name: "Foros", aliases: ["Discusiones", "Comunidades"], related: ["Discord", "Reddit", "Moderación", "Gestión de Comunidad", "Redes Sociales"] },
        { name: "Moderación", aliases: [], related: ["Eventos", "Habilidades Blandas"] },
        { name: "Eventos", aliases: [], related: ["Moderación", "Marketing de Contenidos"] },
        { name: "Herramientas Ofimáticas", aliases: ["Office", "Microsoft Office", "Google Workspace", "Documentos", "Hojas de Cálculo", "Presentaciones", "Word", "Excel", "PowerPoint"], related: ["Presentaciones", "Gestión de Contenidos", "Portafolio"] },
        { name: "Educación Online", aliases: ["E-learning", "Aprendizaje Virtual"], related: ["Tutoría", "Coaching"] },
        { name: "Tutoría", aliases: ["Mentoría", "Acompañamiento", "Asesoría", "Clases"], related: ["Educación Online", "Coaching"] },
        { name: "Coaching", aliases: [], related: ["Tutoría", "Educación Online"] },
        { name: "Investigación Académica", aliases: ["Research"], related: ["Análisis de Datos", "Redacción", "Revista Digital"] },
        { name: "Psicología", aliases: ["Social", "Empatía"], related: ["Habilidades Blandas"] },
    ];

    const entertainment = [
        { name: "Edición de Video", aliases: [], related: ["Postproducción", "Corrección de Color"] },
        { name: "Creador de Contenido", aliases: [], related: ["YouTube", "TikTok", "Instagram"] },
        { name: "Audiovisual", aliases: [], related: ["Producción Musical", "Dirección Audiovisual"] },
        { name: "Producción Musical", aliases: [], related: ["Edición de Audio", "Mezcla de DJ"] },
        { name: "Edición de Audio", aliases: [], related: ["Producción Musical", "Mezcla de DJ"] },
        { name: "Mezcla de DJ", aliases: [], related: ["Producción Musical", "Edición de Audio"] },
        { name: "Animación 3D", aliases: [], related: ["Animación 2D", "Modelado 3D"] },
        { name: "Animación 2D", aliases: [], related: ["Animación 3D", "Storyboard", "Gráficos en Movimiento"] },
        { name: "eSports", aliases: ["Esports", "Gaming Competitivo"], related: ["Videojuegos", "Streaming", "Creador de Contenido"] },
        { name: "Fitness", aliases: ["Entrenamiento", "Deportes", "Sports", "Gym", "Actividad Física"], related: ["Creador de Contenido", "Coreografía"] },
        { name: "Gastronomía", aliases: ["Cocina", "Cooking"], related: ["Creador de Contenido"] },
        { name: "Coreografía", aliases: ["Baile", "Danza", "Trend", "Choreography", "Challenge"], related: ["Actuación", "Fitness"] },
        { name: "Streaming", aliases: [], related: ["Creador de Contenido", "Reels"] },
        { name: "Shorts", aliases: [], related: ["Reels", "YouTube"] },
        { name: "Reels", aliases: [], related: ["Shorts", "Instagram"] },
        { name: "Radio", aliases: [], related: ["Podcast", "Locución"] },
        { name: "Arte Digital", aliases: [], related: ["Concept Art", "Anime", "Gráficos en Movimiento"] },
        { name: "Cortometraje", aliases: [], related: ["Documental", "Dirección de Video"] },
        { name: "Documental", aliases: [], related: ["Cortometraje", "Periodismo"] },
        { name: "Cinematografía", aliases: [], related: ["Dirección de Video", "Fotografía", "Creador de Contenido"] },
        { name: "Fotografía", aliases: [], related: ["Iluminación", "Dirección de Video", "Creador de Contenido"] },
        { name: "Dirección de Video", aliases: [], related: ["Cinematografía", "Storyboard"] },
        { name: "Storyboard", aliases: [], related: ["Dirección de Video", "Animación 2D"] },
        { name: "Artes Plásticas", aliases: ["Artes Visuales", "Pintura", "Escultura", "Dibujo", "Sculpture", "Drawing", "Painting"], related: ["Arte Digital", "Concept Art"] },
        { name: "Actuación", aliases: [], related: ["Doblaje", "Dirección Audiovisual"] },
        { name: "Cosméticos", aliases: ["Maquillaje"], related: ["Dirección de Vestuario", "Actuación", "Creador de Contenido"] },
        { name: "Videojuegos", aliases: [], related: ["Creador de Contenido", "Animación 3D"] },
        { name: "YouTube", aliases: [], related: ["Creador de Contenido", "Shorts"] },
        { name: "TikTok", aliases: [], related: ["Creador de Contenido", "Reels"] },
        { name: "Instagram", aliases: [], related: ["Creador de Contenido", "Reels", "Redes Sociales"] },
        { name: "Facebook", aliases: [], related: ["Creador de Contenido", "Gestión de Comunidad", "Redes Sociales"] },
        { name: "X (Twitter)", aliases: [], related: ["Creador de Contenido", "Redes Sociales"] },
        { name: "Threads", aliases: [], related: ["Creador de Contenido", "Redes Sociales"] },
        { name: "ArtStation", aliases: [], related: ["Arte Digital", "Concept Art"] },
        { name: "Reddit", aliases: [], related: ["Creador de Contenido", "Gestión de Comunidad", "Redes Sociales", "Moderación"] },
        { name: "Discord", aliases: [], related: ["Creador de Contenido", "Gestión de Comunidad", "Redes Sociales", "Moderación"] },
        { name: "Presentador", aliases: ["Host", "Anfitrión"], related: ["Oratoria", "Podcast"] },
        { name: "Influencer", aliases: [], related: ["Creador de Contenido", "Instagram"] },
        { name: "Iluminación", aliases: [], related: ["Fotografía", "Videojuegos"] },
        { name: "Efectos (VFX)", aliases: [], related: ["Animación 3D", "Postproducción"] },
        { name: "Corrección de Color", aliases: [], related: ["Edición de Video", "Postproducción"] },
        { name: "Colaboraciones", aliases: ["Sponsor", "Patrocinio"], related: ["Creador de Contenido", "Influencer", "Alianzas"] },
        { name: "Postproducción", aliases: [], related: ["Edición de Video", "Corrección de Color"] },
        { name: "Composición", aliases: [], related: ["Efectos (VFX)", "Animación 3D"] },
        { name: "Escenografía", aliases: [], related: ["Dirección Audiovisual", "Fotografía"] },
        { name: "Fotomontaje", aliases: [], related: ["Arte Digital", "Corrección de Color"] },
        { name: "Concept Art", aliases: [], related: ["Arte Digital", "ArtStation"] },
        { name: "Stand Up", aliases: ["Comedia", "Humor", "Cuentería"], related: ["Actuación", "Presentador", "Oratoria", "Storytelling", "Creador de Contenido"] },
        { name: "Creación de Personajes", aliases: [], related: ["Animación 3D", "Concept Art"] },
        { name: "Dirección Audiovisual", aliases: [], related: ["Audiovisual", "Actuación"] },
        { name: "Medios Interactivos", aliases: [], related: ["Creador de Contenido", "Videojuegos"] },
        { name: "Curaduría Multimedia", aliases: [], related: ["Colaboraciones", "Alianzas", "Dirección Audiovisual", "Gestión de Comunidad", "Gestión de Contenidos"] }
    ];

    // Unir todos los arrays en uno solo
    const allSkills = [
        ...development,
        ...marketing,
        ...design,
        ...communication,
        ...entertainment,
    ];

    return allSkills;
};
