import { IChats, IMessages, IRequests } from "@/src/core/models/requests/requests.model"
import { IUser } from "@/src/core/models/users/users.model"

// -----------------------------------------------------------------------------
// CURRENT USER
// -----------------------------------------------------------------------------

export const CURRENT_USER: IUser = {
  id: 1,
  name: "Franco",
  lastName: "Coina",
  urlImage: "https://i.pravatar.cc/150?img=12",
  jobTitle: "Frontend Developer",
  description: "Passionate about building scalable UI systems.",
  birthdate: "1995-06-15",
  email: "franco@example.com",
  password: "hashed-password",
  category: "Development",
  phoneNumber: "3001234567",
  abilities: "React, Next.js, TypeScript",
  urlLinkedin: "https://linkedin.com/in/franco",
  urlGithub: "https://github.com/franco",
  urlBehance: "",
  idStateUser: 1,
  idRoleUser: 1,
  nameStateUser: "Active",
  roleName: "Usuario",
  suspensionDate: null,
  reactivationDate: null,
  qualification: 4.8,
  countMatches: 12,
  createdAt: "2026-01-01T00:00:00",
}

// -----------------------------------------------------------------------------
// MOCK USERS
// -----------------------------------------------------------------------------

export const MOCK_USERS: IUser[] = [
  {
    id: 2,
    name: "Mariana",
    lastName: "Piedrahita",
    urlImage: "https://i.pravatar.cc/150?img=5",
    jobTitle: "UX Designer",
    description: "User experience specialist.",
    birthdate: "1994-03-20",
    email: "mariana@example.com",
    password: "hashed",
    category: "Design",
    phoneNumber: "3000000002",
    abilities: "Figma, UX Research",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "https://behance.net/mariana",
    idStateUser: 1,
    idRoleUser: 1,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.5,
    countMatches: 8,
    createdAt: "2026-01-05T00:00:00",
  },
  {
    id: 3,
    name: "Osiris",
    lastName: "Moreno",
    urlImage: "https://i.pravatar.cc/150?img=32",
    jobTitle: "Backend Developer",
    description: "API and microservices expert.",
    birthdate: "1993-09-10",
    email: "osiris@example.com",
    password: "hashed",
    category: "Development",
    phoneNumber: "3000000003",
    abilities: "Node.js, .NET",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "",
    idStateUser: 1,
    idRoleUser: 1,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.6,
    countMatches: 10,
    createdAt: "2026-01-06T00:00:00",
  },
  {
    id: 4,
    name: "Further",
    lastName: "Endless",
    urlImage: "https://i.pravatar.cc/150?img=11",
    jobTitle: "Content Creator",
    description: "Digital content strategist.",
    birthdate: "1992-04-01",
    email: "further@example.com",
    password: "hashed",
    category: "Marketing",
    phoneNumber: "3000000004",
    abilities: "Content Strategy",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "",
    idStateUser: 1,
    idRoleUser: 1,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.3,
    countMatches: 6,
    createdAt: "2026-01-07T00:00:00",
  },
  {
    id: 5,
    name: "Francisco",
    lastName: "Mena",
    urlImage: "https://i.pravatar.cc/150?img=45",
    jobTitle: "Fullstack Developer",
    description: "Building scalable platforms.",
    birthdate: "1990-12-12",
    email: "francisco@example.com",
    password: "hashed",
    category: "Development",
    phoneNumber: "3000000005",
    abilities: "React, Node",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "",
    idStateUser: 1,
    idRoleUser: 1,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.7,
    countMatches: 9,
    createdAt: "2026-01-08T00:00:00",
  },
  {
    id: 6,
    name: "Academy",
    lastName: "Polygon",
    urlImage: "https://i.pravatar.cc/150?img=30",
    jobTitle: "Education Platform",
    description: "Online learning services.",
    birthdate: "2015-01-01",
    email: "academy@example.com",
    password: "hashed",
    category: "Education",
    phoneNumber: "3000000006",
    abilities: "Courses, Mentorship",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "",
    idStateUser: 1,
    idRoleUser: 2,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.9,
    countMatches: 20,
    createdAt: "2026-01-09T00:00:00",
  },
]

// -----------------------------------------------------------------------------
// CHATS (CORREGIDO: estructura real IChats)
// -----------------------------------------------------------------------------

export const MOCK_CHATS: IChats[] = [
  {
    id: 1,
    otherUserId: 1,
    otherUserName: "Jose Angel Rodriguez",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=3",
    lastMessage: "Hola! ¿Como vas?",
    lastMessageDate: "2026-02-24T10:06:00",
    unanswered: true,
  },
  {
    id: 2,
    otherUserId: 2,
    otherUserName: "Mariana Piedrahita",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=5",
    lastMessage: "Que linda vista 😍",
    lastMessageDate: "2026-02-24T10:06:00",
    unanswered: false,
  },
  {
    id: 3,
    otherUserId: 3,
    otherUserName: "Osiris Moreno",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=32",
    lastMessage: "JAJAJAJAJA 🤣",
    lastMessageDate: "2026-02-24T14:03:00",
    unanswered: true,
  },
  {
    id: 4,
    otherUserId: 4,
    otherUserName: "Omar Barrera",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=11",
    lastMessage: "Gracias! Nos alegra que te guste 🙌",
    lastMessageDate: "2026-02-18T12:00:00",
    unanswered: false,
  },
  {
    id: 5,
    otherUserId: 5,
    otherUserName: "Carla Rojas",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=45",
    lastMessage: "Hola, ¿cómo estás?",
    lastMessageDate: "2026-02-17T10:30:00",
    unanswered: false,
  },
  {
    id: 6,
    otherUserId: 6,
    otherUserName: "Karina Oslo",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=30",
    lastMessage: "Gracias por tu interés. Compárteme tu número y mi representante te contactará.",
    lastMessageDate: "2026-02-02T10:15:00",
    unanswered: false,
  },
]

// -----------------------------------------------------------------------------
// MESSAGES (CORREGIDO: incluye senderName y senderUrlImage)
// -----------------------------------------------------------------------------

export const MOCK_MESSAGES: IMessages[] = [
  // ---------------- CHAT 1 (Jose Angel) ----------------
  {
    id: 1,
    content: "Hola! ¿Cómo vas?",
    senderId: 1,
    senderName: "Jose Angel Rodriguez",
    senderUrlImage: "https://i.pravatar.cc/150?img=3",
    receiverId: 11,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 1,
    createdAt: "2026-02-24T10:00:00",
  },
  {
    id: 2,
    content: "Todo bien bro! ¿y tú?",
    senderId: 11,
    senderName: "Franco Coina",
    senderUrlImage: "https://i.pravatar.cc/150?img=12",
    receiverId: 1,
    receiverName: "Jose Angel Rodriguez",
    receiverUrlImage: "https://i.pravatar.cc/150?img=3",
    chatId: 1,
    createdAt: "2026-02-24T10:02:00",
  },

  // ---------------- CHAT 2 (Mariana) ----------------
  {
    id: 3,
    content: "Que linda vista 😍",
    senderId: 2,
    senderName: "Mariana Piedrahita",
    senderUrlImage: "https://i.pravatar.cc/150?img=5",
    receiverId: 11,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 2,
    createdAt: "2026-02-24T10:05:00",
  },
  {
    id: 4,
    content: "Sí! Es brutal ese lugar 🔥",
    senderId: 11,
    senderName: "Franco Coina",
    senderUrlImage: "https://i.pravatar.cc/150?img=12",
    receiverId: 2,
    receiverName: "Mariana Piedrahita",
    receiverUrlImage: "https://i.pravatar.cc/150?img=5",
    chatId: 2,
    createdAt: "2026-02-24T10:06:00",
  },

  // ---------------- CHAT 3 (Osiris) ----------------
  {
    id: 5,
    content: "JAJAJAJAJA 🤣",
    senderId: 3,
    senderName: "Osiris Moreno",
    senderUrlImage: "https://i.pravatar.cc/150?img=32",
    receiverId: 11,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 3,
    createdAt: "2026-02-24T14:02:00",
  },
  {
    id: 6,
    content: "No puedo con eso 😂",
    senderId: 11,
    senderName: "Franco Coina",
    senderUrlImage: "https://i.pravatar.cc/150?img=12",
    receiverId: 3,
    receiverName: "Osiris Moreno",
    receiverUrlImage: "https://i.pravatar.cc/150?img=32",
    chatId: 3,
    createdAt: "2026-02-24T14:03:00",
  },

  // ---------------- CHAT 4 (Further) ----------------
  {
    id: 7,
    content: "Gracias! Nos alegra que te guste 🙌",
    senderId: 4,
    senderName: "Omar Barrera",
    senderUrlImage: "https://i.pravatar.cc/150?img=11",
    receiverId: 11,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 4,
    createdAt: "2026-02-18T11:58:00",
  },
  {
    id: 8,
    content: "Está increíble el contenido 👏",
    senderId: 11,
    senderName: "Franco Coina",
    senderUrlImage: "https://i.pravatar.cc/150?img=12",
    receiverId: 4,
    receiverName: "Omar Barrera",
    receiverUrlImage: "https://i.pravatar.cc/150?img=11",
    chatId: 4,
    createdAt: "2026-02-18T12:00:00",
  },

  // ---------------- CHAT 5 (Francisco) ----------------
  {
    id: 9,
    content: "Hola, ¿cómo estás?",
    senderId: 5,
    senderName: "Carla Rojas",
    senderUrlImage: "https://i.pravatar.cc/150?img=45",
    receiverId: 11,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 5,
    createdAt: "2026-02-17T10:28:00",
  },
  {
    id: 10,
    content: "Todo bien! ¿en qué andas?",
    senderId: 11,
    senderName: "Franco Coina",
    senderUrlImage: "https://i.pravatar.cc/150?img=12",
    receiverId: 5,
    receiverName: "Carla Rojas",
    receiverUrlImage: "https://i.pravatar.cc/150?img=45",
    chatId: 5,
    createdAt: "2026-02-17T10:30:00",
  },

  // ---------------- CHAT 6 (Academy) ----------------
  {
    id: 11,
    content: "Gracias por tu interés. Compárteme tu número y mi representante te contactará.",
    senderId: 6,
    senderName: "Karina Oslo",
    senderUrlImage: "https://i.pravatar.cc/150?img=30",
    receiverId: 11,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 6,
    createdAt: "2026-02-02T10:14:00",
  },
  {
    id: 12,
    content: "Claro! Te lo envío por interno 👍",
    senderId: 11,
    senderName: "Franco Coina",
    senderUrlImage: "https://i.pravatar.cc/150?img=12",
    receiverId: 6,
    receiverName: "Karina Oslo",
    receiverUrlImage: "https://i.pravatar.cc/150?img=30",
    chatId: 6,
    createdAt: "2026-02-02T10:15:00",
  },
];

// -----------------------------------------------------------------------------
// REQUESTS (AHORA CON urlImage)
// -----------------------------------------------------------------------------

export const MOCK_REQUESTS: IRequests[] = [
  {
    id: 1,
    description: "Quiere conectar contigo para hablar sobre un proyecto de desarrollo web.",
    idReceivingUser: 11,
    idRequestingUser: 7,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Monserrat Diaz",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=47",
    idStateRequest: 1,
    createdAt: "2026-02-24T08:00:00",
    updatedAt: null,
  },
  {
    id: 2,
    description: "Le gustaría colaborar en tu próximo proyecto de desarrollo web.",
    idReceivingUser: 11,
    idRequestingUser: 8,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Toshiro Mifune",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=33",
    idStateRequest: 1,
    createdAt: "2026-03-23T15:30:00",
    updatedAt: null,
  },
  {
    id: 3,
    description: "Quiere hacerte una propuesta de trabajo como desarrollador backend.",
    idReceivingUser: 11,
    idRequestingUser: 9,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Jessica Novoa",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=19",
    idStateRequest: 1,
    createdAt: "2026-03-22T11:00:00",
    updatedAt: null,
  },
  {
    id: 4,
    description: "Quiere conectar contigo para hablar sobre un proyecto como desarrollador full-stack.",
    idReceivingUser: 11,
    idRequestingUser: 10,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Tina Beltrán",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=38",
    idStateRequest: 1,
    createdAt: "2026-01-24T08:00:00",
    updatedAt: null,
  },
  {
    id: 5,
    description: "Le gustaría colaborar en tu próximo proyecto desde el área de diseño.",
    idReceivingUser: 11,
    idRequestingUser: 12,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Anita Delgado",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=43",
    idStateRequest: 1,
    createdAt: "2026-02-23T15:30:00",
    updatedAt: null,
  },
  {
    id: 6,
    description: "Quiere hacerte una propuesta de trabajo como QA de software.",
    idReceivingUser: 11,
    idRequestingUser: 13,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Rodrigo Caicedo",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=51",
    idStateRequest: 1,
    createdAt: "2026-02-11T11:00:00",
    updatedAt: null,
  },
]