import { IChats, IMessages, IRequests } from "@/src/core/models/requests/requests.model"
import { IUser } from "@/src/core/models/users/users.model"

// -----------------------------------------------------------------------------
// CURRENT USER
// -----------------------------------------------------------------------------

export const CURRENT_USER: IUser = {
  id: 1,
  name: "Franco",
  lastName: "Coina",
  urlImage: "https://i.pravatar.cc/150?img=12",
  jobTitle: "Frontend Developer",
  description: "Passionate about building scalable UI systems.",
  birthdate: "1995-06-15",
  email: "franco@example.com",
  password: "hashed-password",
  category: "Development",
  phoneNumber: "3001234567",
  abilities: "React, Next.js, TypeScript",
  urlLinkedin: "https://linkedin.com/in/franco",
  urlGithub: "https://github.com/franco",
  urlBehance: "",
  idStateUser: 1,
  idRoleUser: 1,
  nameStateUser: "Active",
  roleName: "Usuario",
  suspensionDate: null,
  reactivationDate: null,
  qualification: 4.8,
  countMatches: 12,
  createdAt: "2026-01-01T00:00:00",
}

// -----------------------------------------------------------------------------
// MOCK USERS
// -----------------------------------------------------------------------------

export const MOCK_USERS: IUser[] = [
  {
    id: 2,
    name: "Mariana",
    lastName: "Piedrahita",
    urlImage: "https://i.pravatar.cc/150?img=5",
    jobTitle: "UX Designer",
    description: "User experience specialist.",
    birthdate: "1994-03-20",
    email: "mariana@example.com",
    password: "hashed",
    category: "Design",
    phoneNumber: "3000000002",
    abilities: "Figma, UX Research",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "https://behance.net/mariana",
    idStateUser: 1,
    idRoleUser: 1,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.5,
    countMatches: 8,
    createdAt: "2026-01-05T00:00:00",
  },
  {
    id: 3,
    name: "Osiris",
    lastName: "Moreno",
    urlImage: "https://i.pravatar.cc/150?img=8",
    jobTitle: "Backend Developer",
    description: "API and microservices expert.",
    birthdate: "1993-09-10",
    email: "osiris@example.com",
    password: "hashed",
    category: "Development",
    phoneNumber: "3000000003",
    abilities: "Node.js, .NET",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "",
    idStateUser: 1,
    idRoleUser: 1,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.6,
    countMatches: 10,
    createdAt: "2026-01-06T00:00:00",
  },
  {
    id: 4,
    name: "Further",
    lastName: "Endless",
    urlImage: "https://i.pravatar.cc/150?img=15",
    jobTitle: "Content Creator",
    description: "Digital content strategist.",
    birthdate: "1992-04-01",
    email: "further@example.com",
    password: "hashed",
    category: "Marketing",
    phoneNumber: "3000000004",
    abilities: "Content Strategy",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "",
    idStateUser: 1,
    idRoleUser: 1,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.3,
    countMatches: 6,
    createdAt: "2026-01-07T00:00:00",
  },
  {
    id: 5,
    name: "Francisco",
    lastName: "Mena",
    urlImage: "https://i.pravatar.cc/150?img=22",
    jobTitle: "Fullstack Developer",
    description: "Building scalable platforms.",
    birthdate: "1990-12-12",
    email: "francisco@example.com",
    password: "hashed",
    category: "Development",
    phoneNumber: "3000000005",
    abilities: "React, Node",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "",
    idStateUser: 1,
    idRoleUser: 1,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.7,
    countMatches: 9,
    createdAt: "2026-01-08T00:00:00",
  },
  {
    id: 6,
    name: "Academy",
    lastName: "Polygon",
    urlImage: "https://i.pravatar.cc/150?img=30",
    jobTitle: "Education Platform",
    description: "Online learning services.",
    birthdate: "2015-01-01",
    email: "academy@example.com",
    password: "hashed",
    category: "Education",
    phoneNumber: "3000000006",
    abilities: "Courses, Mentorship",
    urlLinkedin: "",
    urlGithub: "",
    urlBehance: "",
    idStateUser: 1,
    idRoleUser: 2,
    nameStateUser: "Active",
    roleName: "Usuario",
    suspensionDate: null,
    reactivationDate: null,
    qualification: 4.9,
    countMatches: 20,
    createdAt: "2026-01-09T00:00:00",
  },
]

// -----------------------------------------------------------------------------
// CHATS (CORREGIDO: estructura real IChats)
// -----------------------------------------------------------------------------

export const MOCK_CHATS: IChats[] = [
    {
    id: 1,
    otherUserId: 1,
    otherUserName: "Jose Angel Rodriguez",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=9",
    lastMessage: "Hola Franco! Como vas?",
    lastMessageDate: "2026-02-24T10:06:00",
    unanswered: false,
  },
  {
    id: 2,
    otherUserId: 2,
    otherUserName: "Mariana Piedrahita",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=5",
    lastMessage: "Que linda vista...",
    lastMessageDate: "2026-02-24T10:06:00",
    unanswered: false,
  },
  {
    id: 3,
    otherUserId: 3,
    otherUserName: "Osiris Moreno",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=8",
    lastMessage: "JAJAJAJAJJA",
    lastMessageDate: "2026-02-24T14:03:00",
    unanswered: true,
  },
  {
    id: 4,
    otherUserId: 4,
    otherUserName: "Further Endless",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=15",
    lastMessage: "Gracias! Nos alegra que te guste",
    lastMessageDate: "2026-02-18T12:00:00",
    unanswered: true,
  },
  {
    id: 5,
    otherUserId: 5,
    otherUserName: "Francisco Mena",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=22",
    lastMessage: "Hola, como estas?",
    lastMessageDate: "2026-02-17T10:30:00",
    unanswered: false,
  },
  {
    id: 6,
    otherUserId: 6,
    otherUserName: "Academy Polygon",
    otherUserUrlImage: "https://i.pravatar.cc/150?img=30",
    lastMessage: "Gracias por tu interés. Compártenos tu número y un asesor te contactará.",
    lastMessageDate: "2026-02-02T10:15:00",
    unanswered: true,
  },
]

// -----------------------------------------------------------------------------
// MESSAGES (CORREGIDO: incluye senderName y senderUrlImage)
// -----------------------------------------------------------------------------

export const MOCK_MESSAGES: IMessages[] = [
  {
    id: 1,
    content: "Hola Franco!",
    senderId: 11,
    senderName: "Franco Coina",
    senderUrlImage: "https://i.pravatar.cc/150?img=12",
    receiverId: 1,
    receiverName: "Mariana Piedrahita",
    receiverUrlImage: "https://i.pravatar.cc/150?img=5",
    chatId: 2,
    createdAt: "2026-02-24T10:00:00",
  },
  {
    id: 2,
    content: "Que tal? Como vas?",
    senderId: 11,
    senderName: "Mariana Piedrahita",
    senderUrlImage: "https://i.pravatar.cc/150?img=5",
    receiverId: 1,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 2,
    createdAt: "2026-02-24T10:01:00",
  },
    {
    id: 3,
    content: "Hola Mariana!",
    senderId: 1,
    senderName: "Franco Coina",
    senderUrlImage: "https://i.pravatar.cc/150?img=12",
    receiverId: 11,
    receiverName: "Mariana Piedrahita",
    receiverUrlImage: "https://i.pravatar.cc/150?img=5",
    chatId: 2,
    createdAt: "2026-02-24T10:00:00",
  },
    {
    id: 4,
    content: "JAJAJAJA",
    senderId: 1,
    senderName: "Mariana Piedrahita",
    senderUrlImage: "https://i.pravatar.cc/150?img=5",
    receiverId: 11,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 2,
    createdAt: "2026-02-24T10:00:00",
  },
  {
    id: 5,
    content: "Que linda vista...",
    senderId: 2,
    senderName: "Mariana Piedrahita",
    senderUrlImage: "https://i.pravatar.cc/150?img=5",
    receiverId: 11,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 1,
    createdAt: "2026-02-24T10:01:00",
  },
  {
    id: 6,
    content: "Si, totalmente! Es uno de mis lugares favoritos para trabajar.",
    senderId: 11,
    senderName: "Mariana Piedrahita",
    senderUrlImage: "https://i.pravatar.cc/150?img=5",
    receiverId: 2,
    receiverName: "Franco Coina",
    receiverUrlImage: "https://i.pravatar.cc/150?img=12",
    chatId: 1,
    createdAt: "2026-02-24T10:01:00",
  },
]

// -----------------------------------------------------------------------------
// REQUESTS (AHORA CON urlImage)
// -----------------------------------------------------------------------------

export const MOCK_REQUESTS: IRequests[] = [
  {
    id: 1,
    description: "Quiere conectar contigo para hablar sobre un proyecto.",
    idReceivingUser: 11,
    idRequestingUser: 2,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Mariana Piedrahita",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=5",
    idStateRequest: 1,
    createdAt: "2026-02-24T08:00:00",
    updatedAt: null,
  },
  {
    id: 2,
    description: "Le gustaría colaborar en tu próximo proyecto.",
    idReceivingUser: 11,
    idRequestingUser: 3,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Osiris Moreno",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=8",
    idStateRequest: 1,
    createdAt: "2026-02-23T15:30:00",
    updatedAt: null,
  },
  {
    id: 3,
    description: "Quiere hacerte una propuesta de trabajo.",
    idReceivingUser: 11,
    idRequestingUser: 4,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Further Endless",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=15",
    idStateRequest: 1,
    createdAt: "2026-02-22T11:00:00",
    updatedAt: "2026-02-22T12:00:00",
  },
  {
    id: 4,
    description: "Quiere conectar contigo para hablar sobre un proyecto.",
    idReceivingUser: 11,
    idRequestingUser: 7,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Mariana Piedrahita",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=5",
    idStateRequest: 1,
    createdAt: "2026-02-24T08:00:00",
    updatedAt: null,
  },
  {
    id: 5,
    description: "Le gustaría colaborar en tu próximo proyecto.",
    idReceivingUser: 11,
    idRequestingUser: 6,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Osiris Moreno",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=8",
    idStateRequest: 1,
    createdAt: "2026-02-23T15:30:00",
    updatedAt: null,
  },
  {
    id: 6,
    description: "Quiere hacerte una propuesta de trabajo.",
    idReceivingUser: 11,
    idRequestingUser: 5,
    userNameReceiving: "Franco Coina",
    userNameRequesting: "Further Endless",
    urlImageReceiving: "https://i.pravatar.cc/150?img=12",
    urlImageRequesting: "https://i.pravatar.cc/150?img=15",
    idStateRequest: 1,
    createdAt: "2026-02-22T11:00:00",
    updatedAt: "2026-02-22T12:00:00",
  },
]